name: "CI Checks"
on:
  push:
  pull_request:

jobs:
  test:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: brunojppb/decay-action@0.0.1
        with:
          port: "9000"

      - uses: actions/setup-node@v4

      - name: Reach out to the decay server
        run: curl http://127.0.0.1:8000/ms-joe
